<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { CirclePlus, Search, Refresh, SwitchButton } from "@element-plus/icons-vue";
import { ElMessage } from "element-plus";
import logo from "./assets/zhizhi-logo.png";
import { request, login, saveAccount, ApiError, type Account, type Admin, type Tenant, type Scope } from "./api";
const admin=ref<Admin|null>(null), restoring=ref(true), busy=ref(false), loading=ref(false), saving=ref(false), error=ref("");
const username=ref(""), password=ref(""), accounts=ref<Account[]>([]), tenants=ref<Tenant[]>([]), scopes=ref<Scope[]>([]);
const search=ref(""), status=ref("all"), page=ref(1), open=ref(false), editing=ref<Account|null>(null), scopeLoading=ref(false);
const form=reactive({username:"",display_name:"",email:"",password:"",active:true,selected:[] as string[]});
const key=(item:{tenant_id:string;organization_unit_id:string})=>`${item.tenant_id}:${item.organization_unit_id}`;
const filtered=computed(()=>accounts.value.filter(row=>(status.value==="all"||(row.active?"active":"inactive")===status.value)&&[row.username,row.display_name,row.email].some(value=>value.toLowerCase().includes(search.value.toLowerCase().trim()))));
const canSave=computed(()=>!!form.display_name.trim()&&(!!editing.value||!!form.username.trim())&&((!!editing.value&&!form.password)||form.password.length>=12)&&!scopeLoading.value);
const rows=computed(()=>filtered.value.slice((page.value-1)*20,page.value*20));
function notify(cause:unknown){error.value=cause instanceof Error?cause.message:"请求失败";if(cause instanceof ApiError&&cause.status===401){admin.value=null;open.value=false;form.password="";accounts.value=[];scopes.value=[];}}
async function load(){loading.value=true;error.value="";try{[accounts.value,tenants.value]=await Promise.all([request<Account[]>("/api/admin/accounts"),request<Tenant[]>("/api/admin/organization/tenants")]);page.value=Math.min(page.value,Math.max(1,Math.ceil(filtered.value.length/20)));}catch(cause){notify(cause);}finally{loading.value=false;}}
onMounted(async()=>{try{admin.value=await request<Admin>("/api/admin/auth/me");await load();}catch{admin.value=null;}finally{restoring.value=false;}});
async function signIn(){if(busy.value)return;busy.value=true;error.value="";try{admin.value=await login(username.value.trim(),password.value);password.value="";await load();}catch(cause){notify(cause);}finally{busy.value=false;}}
async function signOut(){await request("/api/admin/auth/logout","POST").catch(()=>undefined);admin.value=null;accounts.value=[];open.value=false;form.password="";}
async function edit(row:Account|null=null){editing.value=row;Object.assign(form,{username:row?.username||"",display_name:row?.display_name||"",email:row?.email||"",password:"",active:row?.active??true,selected:row?.scopes.map(key)||[]});open.value=true;scopeLoading.value=true;error.value="";try{scopes.value=(await Promise.all(tenants.value.map(tenant=>request<Scope[]>(`/api/admin/organization/tenants/${tenant.id}/scopes`)))).flat();}catch(cause){notify(cause);}finally{scopeLoading.value=false;}}
async function save(){if(saving.value||scopeLoading.value)return;if(!form.display_name.trim()||(!editing.value&&!form.username.trim())){ElMessage.warning("请填写用户名和显示名称");return;}if((!editing.value||form.password)&&form.password.length<12){ElMessage.warning("初始或重置密码至少 12 位");return;}saving.value=true;try{const selected=scopes.value.filter(scope=>form.selected.includes(key(scope))).map(({tenant_id,organization_unit_id})=>({tenant_id,organization_unit_id}));await saveAccount({username:form.username,display_name:form.display_name,email:form.email,active:form.active,scopes:selected,password:form.password||undefined},editing.value?.id);open.value=false;form.password="";await load();ElMessage.success("已保存");}catch(cause){notify(cause);}finally{saving.value=false;}}
</script>
<template>
  <div v-if="restoring" class="loading">正在加载…</div>
  <main v-else-if="!admin" class="login-page"><section class="login-card"><div class="brand"><img :src="logo" alt="致知"><div><strong>致知</strong><small>试用账号管理</small></div></div><h1>管理员登录</h1><p>使用现有致知 Super Admin 账号。</p><el-form label-position="top" @submit.prevent="signIn"><el-form-item label="用户名"><el-input v-model="username" autocomplete="username" /></el-form-item><el-form-item label="密码"><el-input v-model="password" type="password" show-password autocomplete="current-password" /></el-form-item><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-button type="primary" native-type="submit" :loading="busy" :disabled="!username.trim()||!password">登录</el-button></el-form></section></main>
  <div v-else class="admin-page"><header class="topbar"><div class="brand"><img :src="logo" alt="致知"><div><strong>致知</strong><small>试用账号管理</small></div></div><div class="admin-info"><el-button :icon="Refresh" circle aria-label="刷新数据" @click="load"/><span>{{ admin.display_name || admin.username }}<small>Super Admin</small></span><el-button :icon="SwitchButton" text @click="signOut">退出</el-button></div></header><main class="body"><section class="page-header"><h1>试用账号</h1><p>管理测试用户及其可使用的租户与组织范围。</p></section><el-alert v-if="error" :title="error" type="error" :closable="false"/><section class="resource"><header class="toolbar"><h2>账号管理</h2><div class="tools"><el-input v-model="search" :prefix-icon="Search" placeholder="搜索用户名、显示名或邮箱" clearable @input="page=1"/><el-segmented v-model="status" :options="[{label:'全部',value:'all'},{label:'启用',value:'active'},{label:'停用',value:'inactive'}]" @change="page=1"/><el-button type="primary" :icon="CirclePlus" @click="edit()">新建账号</el-button></div></header><el-table :data="rows" v-loading="loading" height="100%"><el-table-column label="账号" min-width="180"><template #default="{row}"><strong>{{ row.display_name }}</strong><div class="muted">{{ row.username }}</div></template></el-table-column><el-table-column prop="email" label="邮箱" min-width="180"/><el-table-column label="授权范围" min-width="130"><template #default="{row}">{{ row.scopes.length }} 个范围</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.active?'success':'info'">{{ row.active?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="150" align="right"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑 / 重置密码</el-button></template></el-table-column><template #empty><el-empty :description="search?'没有匹配的账号':'暂无试用账号'" :image-size="70"/></template></el-table><el-pagination v-if="filtered.length" v-model:current-page="page" :page-size="20" :total="filtered.length" layout="total,prev,pager,next"/></section></main></div>
  <el-dialog v-model="open" :title="editing?'编辑试用账号':'新建试用账号'" width="min(56rem,calc(100vw - 2rem))" align-center :close-on-click-modal="false" @closed="form.password=''">
    <el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top"><div class="form-grid"><el-form-item label="用户名" required><el-input v-model="form.username" :disabled="!!editing" maxlength="64" /></el-form-item><el-form-item label="显示名称" required><el-input v-model="form.display_name" maxlength="128"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email" maxlength="320" /></el-form-item><el-form-item :label="editing?'新密码（留空不修改）':'初始密码'" :required="!editing"><el-input v-model="form.password" type="password" show-password autocomplete="new-password" placeholder="至少 12 位" maxlength="256"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.active" active-text="启用" inactive-text="停用"/></el-form-item></div><h3>授权范围</h3><p class="muted">可选择租户范围或任意层级组织。用户只能在被分配的范围中新建会话。</p><el-checkbox-group v-model="form.selected" class="scope-list" v-loading="scopeLoading"><el-checkbox v-for="scope in scopes" :key="key(scope)" :value="key(scope)"><strong>{{ scope.tenant_name }}</strong> · {{ scope.label }}</el-checkbox></el-checkbox-group><el-empty v-if="!scopes.length&&!scopeLoading" description="暂无可选租户" :image-size="60"/></el-form><template #footer><el-button :disabled="saving" @click="open=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">保存</el-button></template>
  </el-dialog>
</template>
